spring.application.name=query-api

clickhouse.enabled=${CLICKHOUSE_ENABLED:true}
clickhouse.url=${CLICKHOUSE_URL:jdbc:clickhouse://localhost:8123/default}
clickhouse.user=${CLICKHOUSE_USER:kien}
clickhouse.password=${CLICKHOUSE_PASSWORD:2606}

nfc.kafka.enabled=${NFC_KAFKA_ENABLED:false}
nfc.kafka.bootstrap-servers=${NFC_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
nfc.kafka.raw-topic=${NFC_KAFKA_RAW_TOPIC:raw-flows}
nfc.kafka.dlq-topic=${NFC_KAFKA_DLQ_TOPIC:dead-letter-flows}
nfc.kafka.client-id=${NFC_KAFKA_CLIENT_ID:network-flow-collector}
nfc.kafka.consumer.enabled=${NFC_KAFKA_CONSUMER_ENABLED:true}
nfc.kafka.consumer.group-id=${NFC_KAFKA_CONSUMER_GROUP_ID:flow-normalization-service}
nfc.kafka.consumer.batch-max-records=${NFC_KAFKA_CONSUMER_BATCH_MAX_RECORDS:5000}

nfc.collectors.enabled=${NFC_COLLECTORS_ENABLED:true}
nfc.collectors.configs.netflow.enabled=${NFC_NETFLOW_ENABLED:false}
nfc.collectors.configs.netflow.properties.bind_address=${NFC_NETFLOW_BIND_ADDRESS:0.0.0.0}
nfc.collectors.configs.netflow.properties.port=${NFC_NETFLOW_PORT:2055}
