services:
  network-flow-collector:
    build:
      context: ..
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
